# Generated by Django 4.2.22 on 2025-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.CharField(max_length=36)),
                ('diseases', models.JSONField()),
                ('symptoms', models.JSONField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='analizer_di_city_664ef2_idx'), models.Index(fields=['created_at'], name='analizer_di_created_08dbc9_idx')],
            },
        ),
    ]
