# Generated by Django 4.2.22 on 2025-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diagnosisrecord',
            name='analizer_di_city_664ef2_idx',
        ),
        migrations.RemoveIndex(
            model_name='diagnosisrecord',
            name='analizer_di_created_08dbc9_idx',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='longitude',
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='patient_ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
