# Generated by Django 4.2.22 on 2025-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizer', '0002_remove_diagnosisrecord_analizer_di_city_664ef2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrecord',
            name='diagnosis_id',
        ),
    ]
