# Generated by Django 4.2.22 on 2025-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
