# Generated by Django 4.2.22 on 2025-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0002_rule_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='MedicalRule',
        ),
    ]
