# Generated by Django 4.2.22 on 2025-06-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system', '0003_rename_rule_medicalrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='question',
            new_name='description',
        ),
    ]
